### PR TITLE
allow newer versions of SpecialFunctions

### PR DESCRIPTION
**Pull request by KristofferC**
Test passes with these as well. Would be nice with a new version with this compat info if possible.

### CODE REVIEW

**Comment by billmclean** [comment]
Kristoffer, I thought setting ``SpecialFunctions = "0.8.0"`` would include all versions from 0.8.0 up to (but not including) 1.0.0.  That is how I read the explanation under 'Version Specifier Format' at [https://julialang.github.io/Pkg.jl/v1/compatibility/](url).

**Comment by KristofferC** [comment]
Nope, see this note https://julialang.github.io/Pkg.jl/v1/compatibility/#Pre-1.0-behavior-1.

`0.8.0` would give you `[0.8.0, 0.9.0)`.

**Comment by billmclean** [comment]
I should have read the next paragraph!

**Comment by KristofferC** [comment]
Thanks for the merge!

**Pull request merged**
